import {
	CodepenGrey,
	CodewarsColored,
	CodewarsGrey,
	DevToColored,
	DevToGrey,
	FacebookColored,
	FacebookGrey,
	FreeCodeCampColored,
	FreeCodeCampGrey,
	FrontendMentorColored,
	FrontendMentorGrey,
	GithubColored,
	GithubGrey,
	GitlabColored,
	GitlabGrey,
	HashnodeColored,
	HashnodeGrey,
	InstagramColored,
	InstagramGrey,
	LinkedInColored,
	LinkedInGrey,
	MediumColored,
	StackOverflowColored,
	StackOverflowGrey,
	TwitchColored,
	TwitchGrey,
	TwitterColored,
	TwitterGrey,
	YoutubeColored,
	YoutubeGrey,
} from "../../../assets/vectors";

const SOCIAL_LINKS = [
	{
		name: "GitHub",
		iconGrey: <GithubGrey />,
		iconColored: <GithubColored />,
		color: "#1A1A1A",
	},
	{
		name: "Frontend Mentor",
		iconGrey: <FrontendMentorGrey />,
		iconColored: <FrontendMentorColored />,
		color: "#fff",
	},
	{
		name: "Twitter",
		iconGrey: <TwitterGrey />,
		iconColored: <TwitterColored />,
		color: "#43B7E9",
	},
	{
		name: "LinkedIn",
		iconGrey: <LinkedInGrey />,
		iconColored: <LinkedInColored />,
		color: "#2D68FF",
	},
	{
		name: "YouTube",
		iconGrey: <YoutubeGrey />,
		iconColored: <YoutubeColored />,
		color: "#EE3939",
	},
	{
		name: "Facebook",
		iconGrey: <FacebookGrey />,
		iconColored: <FacebookColored />,
		color: "#2442AC",
	},
	{
		name: "Instagram",
		iconGrey: <InstagramGrey />,
		iconColored: <InstagramColored />,
		color: "",
	},
	{
		name: "Twitch",
		iconGrey: <TwitchGrey />,
		iconColored: <TwitchColored />,
		color: "#EE3FC8",
	},
	{
		name: "Dev.to",
		iconGrey: <DevToGrey />,
		iconColored: <DevToColored />,
		color: "#333",
	},
	{
		name: "Codewars",
		iconGrey: <CodewarsGrey />,
		iconColored: <CodewarsColored />,
		color: "#8A1A50",
	},
	{
		name: "Codepen",
		iconGrey: <CodepenGrey />,
		iconColored: <CodepenGrey color='white' />,
		color: "#333",
	},
	{
		name: "freeCodeCamp",
		iconGrey: <FreeCodeCampGrey />,
		iconColored: <FreeCodeCampColored />,
		color: "#302267",
	},
	{
		name: "GitLab",
		iconGrey: <GitlabGrey />,
		iconColored: <GitlabColored />,
		color: "#EB4925",
	},
	{
		name: "Hashnode",
		iconGrey: <HashnodeGrey />,
		iconColored: <HashnodeColored />,
		color: "#0330D1",
	},
	{
		name: "Medium",
		iconGrey: <MediumColored />,
		iconColored: <MediumColored />,
		color: "#333",
	},
	{
		name: "Stack Overflow",
		iconGrey: <StackOverflowGrey />,
		iconColored: <StackOverflowColored />,
		color: "#EC7100",
	},
];

export default SOCIAL_LINKS;
